apiVersion: operators.coreos.com/v1
kind: CatalogSourceConfig
metadata:
  name: community-operators
  namespace: openshift-marketplace
spec:
  targetNamespace: namespace-placeholder
  packages: strimzi-kafka-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
